/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ElijahDatePicker {
    'close': () => Promise<void>;
    'color': string;
    'open': () => Promise<void>;
  }
  interface ElijahDisplayDate {}
}

declare global {


  interface HTMLElijahDatePickerElement extends Components.ElijahDatePicker, HTMLStencilElement {}
  var HTMLElijahDatePickerElement: {
    prototype: HTMLElijahDatePickerElement;
    new (): HTMLElijahDatePickerElement;
  };

  interface HTMLElijahDisplayDateElement extends Components.ElijahDisplayDate, HTMLStencilElement {}
  var HTMLElijahDisplayDateElement: {
    prototype: HTMLElijahDisplayDateElement;
    new (): HTMLElijahDisplayDateElement;
  };
  interface HTMLElementTagNameMap {
    'elijah-date-picker': HTMLElijahDatePickerElement;
    'elijah-display-date': HTMLElijahDisplayDateElement;
  }
}

declare namespace LocalJSX {
  interface ElijahDatePicker {
    'color'?: string;
    'onSelectedDateEvent'?: (event: CustomEvent<any>) => void;
  }
  interface ElijahDisplayDate {}

  interface IntrinsicElements {
    'elijah-date-picker': ElijahDatePicker;
    'elijah-display-date': ElijahDisplayDate;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'elijah-date-picker': LocalJSX.ElijahDatePicker & JSXBase.HTMLAttributes<HTMLElijahDatePickerElement>;
      'elijah-display-date': LocalJSX.ElijahDisplayDate & JSXBase.HTMLAttributes<HTMLElijahDisplayDateElement>;
    }
  }
}


