/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ElijahDatePicker {}
}

declare global {


  interface HTMLElijahDatePickerElement extends Components.ElijahDatePicker, HTMLStencilElement {}
  var HTMLElijahDatePickerElement: {
    prototype: HTMLElijahDatePickerElement;
    new (): HTMLElijahDatePickerElement;
  };
  interface HTMLElementTagNameMap {
    'elijah-date-picker': HTMLElijahDatePickerElement;
  }
}

declare namespace LocalJSX {
  interface ElijahDatePicker {}

  interface IntrinsicElements {
    'elijah-date-picker': ElijahDatePicker;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'elijah-date-picker': LocalJSX.ElijahDatePicker & JSXBase.HTMLAttributes<HTMLElijahDatePickerElement>;
    }
  }
}


